"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import datetime
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", cast=bool, default=False)

# Allowed Hosts Configuration
ALLOWED_HOSTS = []
ENV_ALLOWED_HOSTS = config("ENV_ALLOWED_HOSTS", cast=str, default="")
if ENV_ALLOWED_HOSTS:
    ALLOWED_HOSTS = [host.strip() for host in ENV_ALLOWED_HOSTS.split(",")]

# Allow all hosts in development
if DEBUG:
    ALLOWED_HOSTS = ["*"]

# CORS and CSRF Configuration - Set later after CORS_ALLOWED_ORIGINS

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for allauth
    # third party
    "corsheaders",
    "rest_framework",
    "ninja_extra",
    "ninja_jwt",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    # internal
    "waitlists",
    "projects",
    "contact",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Required for allauth
]

ROOT_URLCONF = "core.urls"

# CORS Configuration
CORS_URLS_REGEX = r"^/api/.*$"
CORS_ALLOWED_ORIGINS = []
ENV_CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=str, default="")
if ENV_CORS_ALLOWED_ORIGINS:
    for origin in ENV_CORS_ALLOWED_ORIGINS.split(","):
        origin_clean = origin.strip()
        if origin_clean:
            CORS_ALLOWED_ORIGINS.append(origin_clean)

# CSRF Trusted Origins (built from CORS allowed origins)
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Uncomment to allow all origins in development (not recommended)
# if DEBUG:
#     CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DATABASE_URL = config("DATABASE_URL", cast=str, default="")
if DATABASE_URL != "":
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=300,
            conn_health_checks=True
        )
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "static"

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR.parent / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if DEBUG:
    NINJA_JWT = {
        'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=60),
        'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    }

# Django Sites Framework (required for allauth)
SITE_ID = 1

# Email Configuration
EMAIL_BACKEND = config("EMAIL_BACKEND", cast=str, default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", cast=str, default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", cast=str, default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", cast=str, default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", cast=str, default="noreply@digitalpathai.com")

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin
    "django.contrib.auth.backends.ModelBackend",
    # Allauth specific authentication methods
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth settings
ACCOUNT_LOGIN_METHODS = {"username", "email"}  # Allow login with username or email
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Email verification is mandatory for regular signups
ACCOUNT_EMAIL_SUBJECT_PREFIX = "DigitalPath AI - "
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]  # Required fields for signup
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # No email verification needed for social accounts (email already verified by provider)
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create account for social logins
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

# Frontend URL for email verification (Next.js)
FRONTEND_URL = config("FRONTEND_URL", cast=str, default="http://localhost:3000")

# Social Account Adapter (custom for headless/JWT setup)
SOCIALACCOUNT_ADAPTER = "helpers.socialaccount_adapter.CustomSocialAccountAdapter"

# Social Account Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
    "github": {
        "SCOPE": [
            "user",
            "user:email",
        ],
    },
}

# For development: print emails to console (commented out to enable real email sending)
# if DEBUG:
#     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Celery Configuration
CELERY_BROKER_URL = config("CELERY_BROKER_URL", cast=str, default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", cast=str, default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE